### ISSUE TITLE
working

### ISSUE THREAD

**Issue by darkzbaron** [exofudge/Pocket-Casts#1]
Hey, im getting tons of errors. Did i get the latest version?
Thanks for the great work by the way ;)

**Comment by furgoose** [comment]
It's in a very early state at the moment. What errors are you getting? And what version of python?

**Comment by darkzbaron** [comment]
Hey, it looks like I went too fast. It is working I used the wrong version of python. Good catch!,

**Comment by darkzbaron** [comment]
hey, congrats on your progress. I was about to ask you if there was the possibility to update podcast status but it seems like it is something you already thought about.

I am just having some difficulty with the synthax. Would you mind providing me with an example on how to use 
pocket. update_starred(podcast, episode, starred)?

Thanks,Jonathan

**Comment by furgoose** [comment]
The easiest way to use update_starred is with the getters and setters of the episode class, which call the method behind the scenes e.g.

```python
>>> import pocketcasts
>>> p = pocketcasts.Pocketcasts(user, password)
# Just getting a podcast episode to star
>>> podcast = p.get_featured()[0]
>>> episode = p.get_podcast_episodes(podcast)[0]
>>> episode.starred
False
>>> episode.starred = True
>>> episode.starred
True
```

If you did want to use the method, the syntax is using a pocketcasts.Podcast class, a pocketcasts.Episode class and a boolean.

**Comment by darkzbaron** [comment]
Great, thanks so much!
