### ISSUE TITLE
Question: Does it work with https://playbeta.pocketcasts.com

### ISSUE THREAD

**Issue by ghost** [exofudge/Pocket-Casts#3]
Hey up, 

Just checking whether this api works with their beta version. I assume the api is the same, but I wanted to check if anyone tested it already. 

https://playbeta.pocketcasts.com

🙌

**Comment by furgoose** [comment]
I'm currently working on a new version that implements that API, it's progress is in the [updates branch](https://github.com/furgoose/Pocket-Casts/tree/updates)
